-- Clear all data
TRUNCATE TABLE inventory_history, inventory RESTART IDENTITY CASCADE;

-- Insert inventory data
INSERT INTO inventory(id, product_code, quantity, created_at, updated_at) VALUES
    (1, 'P100', 100, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (2, 'P101', 85, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (3, 'P102', 60, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (4, 'P103', 45, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (5, 'P104', 120, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (6, 'P105', 30, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (7, 'P106', 75, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (8, 'P107', 90, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (9, 'P108', 40, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (10, 'P109', 55, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (11, 'P110', 25, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (12, 'P111', 15, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (13, 'P112', 35, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (14, 'P113', 20, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (15, 'P114', 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
